version: "3.8"

services:
  library-postgres:
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - posgres_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54432:5432
  library-services:
    image: library-services:0.1.0-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - library-postgres
    ports:
      - 8090:8080
    environment:
      - POSTGRES_HOST=library-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  posgres_db_volume: